#!/bin/bash
# claude-rename installer — sets up the auto-naming hook for Claude Code
# Usage: curl -sL https://raw.githubusercontent.com/sathwick-p/claude-rename/main/install.sh | bash

set -euo pipefail

HOOK_URL="https://raw.githubusercontent.com/sathwick-p/claude-rename/main/src/hook.mjs"
PROMPT_URL="https://raw.githubusercontent.com/sathwick-p/claude-rename/main/src/title-prompt.mjs"
HOOK_DIR="$HOME/.claude/hooks"
HOOK_FILE="$HOOK_DIR/claude-rename.mjs"
PROMPT_FILE="$HOOK_DIR/title-prompt.mjs"
RUNNER_FILE="$HOOK_DIR/claude-rename-runner.sh"
SETTINGS_FILE="$HOME/.claude/settings.json"
HOOK_COMMAND='"$HOME/.claude/hooks/claude-rename-runner.sh"'

# Detect the current node binary path for the fast path in runner script
DETECTED_NODE="$(command -v node 2>/dev/null || true)"
if [ -z "$DETECTED_NODE" ]; then
  echo "Warning: node not found in PATH. The hook will search common locations at runtime."
  DETECTED_NODE="/usr/local/bin/node"
fi

echo "Installing claude-rename hook..."
echo ""

# 1. Download hook files
mkdir -p "$HOOK_DIR"
curl -fsSL "$HOOK_URL" -o "$HOOK_FILE"
echo "  Hook downloaded to $HOOK_FILE"
curl -fsSL "$PROMPT_URL" -o "$PROMPT_FILE"
echo "  Prompt helper downloaded to $PROMPT_FILE"

# 2. Generate runner script (finds node across NVM/fnm/volta/system)
cat > "$RUNNER_FILE" << RUNNER_EOF
#!/bin/sh
# claude-rename hook runner — finds node regardless of shell/PATH setup
# Generated by install.sh. Re-run installer to update.

# Fast path: node binary detected at install time
if [ -x "$DETECTED_NODE" ]; then
  exec "$DETECTED_NODE" "\$HOME/.claude/hooks/claude-rename.mjs" "\$@"
fi

# Fallback: search for node in common locations
NODE_BIN="\$(command -v node 2>/dev/null)"

# NVM (most common version manager)
if [ -z "\$NODE_BIN" ] && [ -d "\$HOME/.nvm/versions/node" ]; then
  NODE_BIN="\$(ls -1d "\$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | tail -1)"
fi

# fnm
if [ -z "\$NODE_BIN" ] && [ -d "\$HOME/.fnm/node-versions" ]; then
  NODE_BIN="\$(ls -1d "\$HOME"/.fnm/node-versions/*/installation/bin/node 2>/dev/null | tail -1)"
fi
if [ -z "\$NODE_BIN" ] && [ -d "\$HOME/Library/Application Support/fnm/node-versions" ]; then
  NODE_BIN="\$(ls -1d "\$HOME/Library/Application Support/fnm/node-versions"/*/installation/bin/node 2>/dev/null | tail -1)"
fi

# volta
if [ -z "\$NODE_BIN" ] && [ -x "\$HOME/.volta/bin/node" ]; then
  NODE_BIN="\$HOME/.volta/bin/node"
fi

# Homebrew (Apple Silicon + Intel) and system
if [ -z "\$NODE_BIN" ]; then
  for p in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    if [ -x "\$p" ]; then NODE_BIN="\$p"; break; fi
  done
fi

# Not found — fail silently so we never block Claude Code
if [ -z "\$NODE_BIN" ]; then
  echo '{"continue":true,"suppressOutput":true}'
  exit 0
fi

exec "\$NODE_BIN" "\$HOME/.claude/hooks/claude-rename.mjs" "\$@"
RUNNER_EOF
chmod +x "$RUNNER_FILE"
echo "  Runner script created at $RUNNER_FILE"

# 3. Register in settings.json using Node (always available with Claude Code)
"$DETECTED_NODE" -e "
const fs = require('fs');
const path = '$SETTINGS_FILE';
const cmd = '$HOOK_COMMAND';

let settings = {};
try { settings = JSON.parse(fs.readFileSync(path, 'utf-8')); } catch {}

if (!settings.hooks) settings.hooks = {};
if (!settings.hooks.Stop) settings.hooks.Stop = [];

const already = settings.hooks.Stop.some(e =>
  (e.hooks || []).some(h => h.command && h.command.includes('claude-rename'))
);

if (!already) {
  settings.hooks.Stop.push({ hooks: [{ type: 'command', command: cmd }] });
  fs.writeFileSync(path, JSON.stringify(settings, null, 4));
  console.log('  Hook registered in settings.json');
} else {
  console.log('  Hook already registered in settings.json');
}
"

echo ""
echo "Done! New sessions will be auto-named after the first exchange."
echo "No API key needed — uses your existing Claude Code subscription."
echo ""
echo "For CLI tools (list, backfill, rename), run:"
echo "  npx github:sathwick-p/claude-rename <command>"
echo ""
